// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'music/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_cover_cache_dir`, `global_playback_session`, `open_scan_conn`, `open_stats_conn`, `parse_device`, `parse_media`, `parse_remote_source`

/// 解析原始歌词文本（LRC/YRC/QRC/ESLRC/TTML/Lys 等），
/// 返回 [`StructuredLyricsPayload`] 的 JSON（camelCase）。
///
/// 包含 `document`（解析出的多轨结构）、`semanticLines`（语义行）和
/// `displayLines`（可直接用于逐行/逐字播放的展示行，含 translation/romaji）。
/// 解析失败或空文本时返回合法 JSON 结构而非错误。
Future<String> parseLyrics({required String rawLyrics}) =>
    RustLib.instance.api.crateApiParseLyrics(rawLyrics: rawLyrics);

/// 搜索音乐源。`source` ∈ `kw`/`kg`/`tx`/`wy`/`mg`。
/// 返回 [`LxSearchItem`] 数组的 JSON；失败返回错误信息。
Future<String> lxSearch({
  required String source,
  required String keyword,
  required int limit,
}) => RustLib.instance.api.crateApiLxSearch(
  source: source,
  keyword: keyword,
  limit: limit,
);

/// QQ 专辑搜索（签名 Desktop 接口 search_type=2）。
/// 返回原始专辑条目数组的 JSON；失败返回错误信息。
Future<String> txSearchAlbums({
  required String keyword,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiTxSearchAlbums(
  keyword: keyword,
  page: page,
  limit: limit,
);

/// QQ 专辑曲目（签名 AlbumSongList 接口，按 albumMid）。
/// 返回 [`LxSearchItem`] 数组的 JSON；失败返回错误信息。
Future<String> txAlbumSongs({
  required String albumMid,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiTxAlbumSongs(
  albumMid: albumMid,
  page: page,
  limit: limit,
);

/// 批量查询 QQ 歌曲时长（UniformRuleCtrl，按 songid，每批≤50）。
/// 入参为 songid 数组 JSON（如 `[123,456]`），返回 `{ "id": 秒 }` 的 JSON。
Future<String> txBatchTrackInterval({required String songIdsJson}) =>
    RustLib.instance.api.crateApiTxBatchTrackInterval(songIdsJson: songIdsJson);

/// LX 歌单搜索（kw/kg/tx/wy/mg 原生歌单接口，对齐桌面端 searchLxPlaylists）。
/// 返回归一化 [`crate::music::lx_catalog::LxPlaylistItem`] 数组的 JSON。
Future<String> lxSearchPlaylists({
  required String source,
  required String keyword,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiLxSearchPlaylists(
  source: source,
  keyword: keyword,
  page: page,
  limit: limit,
);

/// LX 歌单曲目（对齐桌面端 lxGetPlaylistTracks，含 TX 风控 Web 兜底）。
/// 返回 `{ list: [LxSearchItem], isEnd: bool }` 的 JSON。
Future<String> lxPlaylistTracks({
  required String source,
  required String playlistId,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiLxPlaylistTracks(
  source: source,
  playlistId: playlistId,
  page: page,
  limit: limit,
);

/// LX 专辑曲目（对齐桌面端 lxGetAlbumSongs，kw/kg/tx/wy/mg 原生专辑接口）。
/// 返回 [`crate::music::lx_search::LxSearchItem`] 数组的 JSON。
/// album_id 无效（可能是回退的专辑名）时返回空数组，由调用方走搜索回退。
Future<String> lxAlbumSongs({
  required String source,
  required String albumId,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiLxAlbumSongs(
  source: source,
  albumId: albumId,
  page: page,
  limit: limit,
);

/// 从指定音源抓取歌词（kg/kw/tx/wy）。
///
/// - `song_info_json`：[
/// `LyricSongInfo`] 的 JSON（camelCase）
///
/// 返回 [`LyricResult`]（含 lyric/tlyric/rlyric/lxlyric）的 JSON；
/// 该音源无歌词返回 `"null"`。
Future<String> fetchLyricFromSource({
  required String source,
  required String songInfoJson,
}) => RustLib.instance.api.crateApiFetchLyricFromSource(
  source: source,
  songInfoJson: songInfoJson,
);

/// 测试 WebDAV 连接（列出根目录）。
Future<void> webdavTestConnection({required String sourceJson}) =>
    RustLib.instance.api.crateApiWebdavTestConnection(sourceJson: sourceJson);

/// 按表单连接信息浏览 WebDAV 目录（新增源未保存时也可浏览，返回 [`RemoteFileEntry[]`] JSON）。
Future<String> webdavBrowseDirectory({
  required String sourceJson,
  required String path,
}) => RustLib.instance.api.crateApiWebdavBrowseDirectory(
  sourceJson: sourceJson,
  path: path,
);

/// 按已保存远程源测试连接：读取存储凭证（含密码），叠加表单覆盖项后 PROPFIND 根目录。
///
/// 用于编辑场景：密码输入框留空表示沿用原密码，仅测试连接无需先保存。
Future<void> webdavTestSavedSource({
  required String dbPath,
  required String sourceId,
  required String overridesJson,
}) => RustLib.instance.api.crateApiWebdavTestSavedSource(
  dbPath: dbPath,
  sourceId: sourceId,
  overridesJson: overridesJson,
);

/// 播放前直接读取文件 ReplayGain 标签并计算 Linear Gain（无 DB 缓存）。
///
/// 无标签 / 读取失败返回 1.0（原始音量播放）。
Future<double> loudnessPlaybackGainForFile({
  required String filePath,
  required double gainOffsetDb,
  required bool preventClipping,
}) => RustLib.instance.api.crateApiLoudnessPlaybackGainForFile(
  filePath: filePath,
  gainOffsetDb: gainOffsetDb,
  preventClipping: preventClipping,
);

/// 查询指定歌曲的响度分析缓存记录（LUFS/峰值等），返回 `LoudnessRecord` JSON。
/// 无记录返回 `"null"`。
Future<String> getTrackLoudnessInfo({
  required String dbPath,
  required PlatformInt64 songId,
}) => RustLib.instance.api.crateApiGetTrackLoudnessInfo(
  dbPath: dbPath,
  songId: songId,
);

/// 记录一次播放事件（含聚合统计与播放历史）。
///
/// - `db_path`：SQLite 数据库文件路径
/// - `payload_json`：[`RecordPlayPayload`] 的 JSON（camelCase，如
///   `{"songPath":"...","listenedMs":30000,"durationMs":195000,"title":"...","artist":"..."}`）
Future<void> statsRecordPlay({
  required String dbPath,
  required String payloadJson,
}) => RustLib.instance.api.crateApiStatsRecordPlay(
  dbPath: dbPath,
  payloadJson: payloadJson,
);

/// 获取三个周期的听歌时长（日/周/总），返回 JSON 秒数。
Future<String> statsGetListenDurations({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetListenDurations(dbPath: dbPath);

/// 获取行为统计（Top 歌曲/歌手/专辑、时段分布、近期活跃）。
///
/// - `time_range_json`：[`TimeRange`] 的 JSON（如 `{"type":"Days30"}`）
Future<String> statsGetBehaviorStats({
  required String dbPath,
  required String timeRangeJson,
}) => RustLib.instance.api.crateApiStatsGetBehaviorStats(
  dbPath: dbPath,
  timeRangeJson: timeRangeJson,
);

/// 获取最近播放历史（去重，按播放时间倒序）。
Future<String> statsGetRecentHistory({required String dbPath, BigInt? limit}) =>
    RustLib.instance.api.crateApiStatsGetRecentHistory(
      dbPath: dbPath,
      limit: limit,
    );

/// 添加一条最近播放记录。
Future<void> statsAddToHistory({
  required String dbPath,
  required String songPath,
}) => RustLib.instance.api.crateApiStatsAddToHistory(
  dbPath: dbPath,
  songPath: songPath,
);

/// 清空最近播放历史。
Future<void> statsClearRecentHistory({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsClearRecentHistory(dbPath: dbPath);

/// 从最近播放历史移除指定歌曲。
Future<void> statsRemoveFromRecentHistory({
  required String dbPath,
  required List<String> songPaths,
}) => RustLib.instance.api.crateApiStatsRemoveFromRecentHistory(
  dbPath: dbPath,
  songPaths: songPaths,
);

/// 导出统计备份到 JSON 文件。
///
/// - `options_json`：[`StatisticsExportOptions`] 的 JSON（camelCase，含 `filePath`/`includeRecentPlays`）
Future<String> statsExportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsExportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 预览统计备份导入（不写库）。
Future<String> statsPreviewStatisticsImport({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsPreviewStatisticsImport(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 导入统计备份。
///
/// - `options_json`：[`StatisticsImportOptions`] 的 JSON（camelCase，
///   含 `filePath`/`mode`("overwrite"|"merge")/`continueDuplicateImport`）
Future<String> statsImportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsImportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 增量扫描一个音乐文件夹，将新增/更新/删除写入数据库，返回该文件夹全部歌曲 JSON。
///
/// - `db_path`：SQLite 数据库文件路径
/// - `folder_path`：要扫描的文件夹路径
/// - `minimum_duration_seconds`：低于该时长的歌曲被过滤（0 表示不过滤）
Future<String> scanMusicFolder({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
  List<String>? allowedFormats,
}) => RustLib.instance.api.crateApiScanMusicFolder(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
  allowedFormats: allowedFormats,
);

/// 批量解析一组音频文件的元数据（不写库），返回 `Song[]` JSON。对齐桌面端 `parse_audio_files`。
Future<String> parseAudioFiles({
  required List<String> paths,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiParseAudioFiles(
  paths: paths,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 递归扫描文件夹内全部受支持音频并解析元数据（不写库），返回 `Song[]` JSON。
/// 对齐桌面端 `parse_music_folder`。
Future<String> parseMusicFolder({
  required String folderPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiParseMusicFolder(
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// Android SAF：从一个已被 Android 侧通过 ContentResolver 打开的 fd 解析单个音频，
/// 返回曲库 [`Song`] JSON。读取走 `/proc/self/fd/<fd>`，解析逻辑与路径扫描完全一致。
Future<String> parseAudioFromFdAndroid({
  required int fd,
  required String fileName,
  required String pathKey,
  required String format,
}) => RustLib.instance.api.crateApiParseAudioFromFdAndroid(
  fd: fd,
  fileName: fileName,
  pathKey: pathKey,
  format: format,
);

/// Android SAF：从已物化到应用内部存储的真实文件路径解析单个音频。
///
/// 解析逻辑与路径扫描完全一致，`path_key` 仍为稳定的 SAF content URI，作为
/// 曲库 [`Song`].path 主键；`file_name` 用于派生展示用 name/title。
/// 相比读取 `/proc/self/fd/{fd}`，真实路径读取在部分机型/提供方下更可靠。
Future<String> parseAudioFromPathAndroid({
  required String filePath,
  required String fileName,
  required String pathKey,
  required String format,
}) => RustLib.instance.api.crateApiParseAudioFromPathAndroid(
  filePath: filePath,
  fileName: fileName,
  pathKey: pathKey,
  format: format,
);

/// Android SAF：从物化后的真实文件路径提取内嵌封面，缓存别名按 `source_key`（content URI）。
Future<String> extractSongCoverThumbnailFromPath({
  required String cacheRoot,
  required String sourceKey,
  required String realPath,
}) => RustLib.instance.api.crateApiExtractSongCoverThumbnailFromPath(
  cacheRoot: cacheRoot,
  sourceKey: sourceKey,
  realPath: realPath,
);

/// Android SAF：把一批已解析歌曲增量提交到 `folder_key`（SAF tree documentId）名下。
/// 复用桌面同款增量 diff，保证新增/变更/删除在库内一致。
Future<String> scanSafSongsCommit({
  required String dbPath,
  required String folderKey,
  required String songsJson,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiScanSafSongsCommit(
  dbPath: dbPath,
  folderKey: folderKey,
  songsJson: songsJson,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 列出全部远程源（返回 [`RemoteSource`] 数组 JSON）。
Future<String> listRemoteSources({required String dbPath}) =>
    RustLib.instance.api.crateApiListRemoteSources(dbPath: dbPath);

/// 新增或更新远程源（按 `RemoteSourceInput` JSON，缺 id 则新增）。
Future<String> saveRemoteSource({
  required String dbPath,
  required String sourceJson,
}) => RustLib.instance.api.crateApiSaveRemoteSource(
  dbPath: dbPath,
  sourceJson: sourceJson,
);

/// 删除远程源及其关联歌曲。
Future<void> removeRemoteSource({
  required String dbPath,
  required String sourceId,
}) => RustLib.instance.api.crateApiRemoveRemoteSource(
  dbPath: dbPath,
  sourceId: sourceId,
);

/// 同步远程源：扫描远程目录、增量解析并写入音乐库。
///
/// - `cache_root`：远程音频缓存根目录（调用方传入 app 缓存目录）
/// - `source_id`：远程源 id
///
/// 返回 [`RemoteSyncResult`] JSON。
Future<String> syncRemoteSource({
  required String dbPath,
  required String cacheRoot,
  required String sourceId,
}) => RustLib.instance.api.crateApiSyncRemoteSource(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  sourceId: sourceId,
);

/// 查询远程音频缓存占用（返回 [`RemoteCacheUsage`] JSON）。
Future<String> getRemoteCacheUsage({required String cacheRoot}) =>
    RustLib.instance.api.crateApiGetRemoteCacheUsage(cacheRoot: cacheRoot);

/// 清空远程音频缓存（返回清空后 [`RemoteCacheUsage`] JSON）。
Future<String> clearRemoteCache({required String cacheRoot}) =>
    RustLib.instance.api.crateApiClearRemoteCache(cacheRoot: cacheRoot);

/// 解析远程音乐播放来源：已缓存返回本地路径，未缓存返回直链流。
///
/// 返回 `{"kind":"cached","path":...}` 或 `{"kind":"stream","url":...,...}` JSON。
Future<String> remotePlaybackSource({
  required String dbPath,
  required String remoteUri,
}) => RustLib.instance.api.crateApiRemotePlaybackSource(
  dbPath: dbPath,
  remoteUri: remoteUri,
);

/// 向账号 API 发起带签名的 POST 请求（返回响应 JSON）。
Future<String> authAuthedRequest({
  required String dataDir,
  required String action,
  required String bodyJson,
  BigInt? fetchTimeoutMs,
}) => RustLib.instance.api.crateApiAuthAuthedRequest(
  dataDir: dataDir,
  action: action,
  bodyJson: bodyJson,
  fetchTimeoutMs: fetchTimeoutMs,
);

/// 保存认证凭证（token + user JSON 写入 auth 目录）。
Future<void> authSaveCredentials({
  required String dataDir,
  required String token,
  required String userJson,
}) => RustLib.instance.api.crateApiAuthSaveCredentials(
  dataDir: dataDir,
  token: token,
  userJson: userJson,
);

/// 读取认证凭证（返回 `AuthCredentials` JSON 或 null）。
Future<String> authGetCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthGetCredentials(dataDir: dataDir);

/// 清除认证凭证。
Future<void> authClearCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthClearCredentials(dataDir: dataDir);

/// 设置 API 基地址。
Future<void> authSetBaseUrl({
  required String dataDir,
  required String baseUrl,
}) => RustLib.instance.api.crateApiAuthSetBaseUrl(
  dataDir: dataDir,
  baseUrl: baseUrl,
);

/// 设置 API 签名密钥。
Future<void> authSetApiSecret({
  required String dataDir,
  required String apiSecret,
}) => RustLib.instance.api.crateApiAuthSetApiSecret(
  dataDir: dataDir,
  apiSecret: apiSecret,
);

/// 读取音乐库文件夹（返回 `LibraryFolder[]` JSON，含歌曲数）。
Future<String> getLibraryFolders({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryFolders(dbPath: dbPath);

/// 新增音乐库文件夹。
Future<void> addLibraryFolder({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiAddLibraryFolder(dbPath: dbPath, path: path);

/// 移除音乐库文件夹及其后代歌曲。
Future<void> removeLibraryFolder({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiRemoveLibraryFolder(
  dbPath: dbPath,
  path: path,
);

/// 读取全部本地曲库歌曲（返回 `LibrarySong[]` JSON）。
Future<String> getLibrarySongsCached({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibrarySongsCached(dbPath: dbPath);

/// 按路径批量查询歌曲（返回 `LibrarySong[]` JSON）。
Future<String> getLibrarySongsByPaths({
  required String dbPath,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGetLibrarySongsByPaths(
  dbPath: dbPath,
  paths: paths,
);

/// 搜索本地音乐库（返回 `LibrarySong[]` JSON）。
Future<String> searchLibrarySongs({
  required String dbPath,
  required String query,
  BigInt? limit,
}) => RustLib.instance.api.crateApiSearchLibrarySongs(
  dbPath: dbPath,
  query: query,
  limit: limit,
);

/// 读取歌手目录（返回 `ArtistCatalogItem[]` JSON）。
Future<String> getLibraryArtistCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryArtistCatalog(dbPath: dbPath);

/// 读取专辑目录（返回 `AlbumCatalogItem[]` JSON）。
Future<String> getLibraryAlbumCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryAlbumCatalog(dbPath: dbPath);

/// 按歌手名获取歌曲路径列表。
Future<String> getLibrarySongPathsByArtist({
  required String dbPath,
  required String artistName,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByArtist(
  dbPath: dbPath,
  artistName: artistName,
);

/// 按专辑 key 获取歌曲路径列表。
Future<String> getLibrarySongPathsByAlbum({
  required String dbPath,
  required String albumKey,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByAlbum(
  dbPath: dbPath,
  albumKey: albumKey,
);

/// 文件夹视图的歌曲路径列表（支持查询过滤与排序）。
///
/// - `sort_mode`：`"title"`/`"name"`/`"artist"`/`"addedAt"`/`"addedAtAsc"`/`"trackNumber"`
Future<String> getLibrarySongPathsForFolderView({
  required String dbPath,
  required String folderPath,
  String? query,
  required String sortMode,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsForFolderView(
  dbPath: dbPath,
  folderPath: folderPath,
  query: query,
  sortMode: sortMode,
);

/// 递归构建音乐库文件夹目录树（返回 `FolderNode[]` JSON）。
Future<String> getLibraryHierarchy({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryHierarchy(dbPath: dbPath);

/// 获取歌曲缩略图封面（远程 URI 先缓存到本地），返回缓存路径字符串。
Future<String> getSongCoverThumbnail({
  required String dbPath,
  required String cacheRoot,
  required String path,
}) => RustLib.instance.api.crateApiGetSongCoverThumbnail(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  path: path,
);

/// 获取歌曲高清封面（远程 URI 先缓存到本地），返回缓存路径字符串。
Future<String> getSongCover({
  required String dbPath,
  required String cacheRoot,
  required String path,
}) => RustLib.instance.api.crateApiGetSongCover(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  path: path,
);

/// 扫描 SAF 歌曲时从已打开的 fd 提取内嵌封面并写入封面缓存。
///
/// 读文件走 `/proc/self/fd/{fd}`，按 content URI 路径哈希写别名，使列表展示时
/// `get_song_cover_thumbnail` 能直接命中缓存而无需再读 content URI。返回缓存路径。
Future<String> extractSongCoverThumbnailFromFd({
  required String cacheRoot,
  required String path,
  required int fd,
}) => RustLib.instance.api.crateApiExtractSongCoverThumbnailFromFd(
  cacheRoot: cacheRoot,
  path: path,
  fd: fd,
);

/// 读取并解析歌曲歌词（返回 `StructuredLyricsPayload` JSON）。
Future<String> getSongLyricsPayload({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiGetSongLyricsPayload(
  dbPath: dbPath,
  path: path,
);

/// 读取歌曲歌词用于编辑（返回 `SongLyricsForEdit` JSON）。
Future<String> getSongLyricsForEdit({required String path}) =>
    RustLib.instance.api.crateApiGetSongLyricsForEdit(path: path);

/// 保存歌曲歌词（内嵌或侧边 LRC），返回 `SongLyricsForEdit` JSON。
Future<String> saveSongLyrics({
  required String path,
  required String lyrics,
  required LyricsStorageSource source,
  String? sourcePath,
}) => RustLib.instance.api.crateApiSaveSongLyrics(
  path: path,
  lyrics: lyrics,
  source: source,
  sourcePath: sourcePath,
);

/// 读取歌曲完整歌词（内嵌标签 → 侧边 LRC，远程歌曲走源 + 缓存），返回原始歌词文本。
Future<String> getSongLyrics({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiGetSongLyrics(dbPath: dbPath, path: path);

/// 读取用户主动选择的 .lrc 歌词文件源码（返回解码后的歌词文本）。
Future<String> readLyricsFile({required String path}) =>
    RustLib.instance.api.crateApiReadLyricsFile(path: path);

/// 保存歌曲背景图到背景根目录下 `song_backgrounds/` 并写入数据库，返回保存后的背景图路径。
Future<String> saveSongBackground({
  required String dbPath,
  required String songBackgroundsRoot,
  required String songPath,
  required String backgroundPath,
}) => RustLib.instance.api.crateApiSaveSongBackground(
  dbPath: dbPath,
  songBackgroundsRoot: songBackgroundsRoot,
  songPath: songPath,
  backgroundPath: backgroundPath,
);

/// 查询歌曲背景图路径，无则返回 JSON `null`。
Future<String> getSongBackground({
  required String dbPath,
  required String songPath,
}) => RustLib.instance.api.crateApiGetSongBackground(
  dbPath: dbPath,
  songPath: songPath,
);

/// 清除歌曲背景图（删除本地文件 + 数据库记录）。
Future<void> clearSongBackground({
  required String dbPath,
  required String songBackgroundsRoot,
  required String songPath,
}) => RustLib.instance.api.crateApiClearSongBackground(
  dbPath: dbPath,
  songBackgroundsRoot: songBackgroundsRoot,
  songPath: songPath,
);

/// 保存歌曲信息标签（返回 `SaveSongInfoResponse` JSON）。
Future<String> saveSongInfo({
  required String dbPath,
  required String path,
  required String payloadJson,
}) => RustLib.instance.api.crateApiSaveSongInfo(
  dbPath: dbPath,
  path: path,
  payloadJson: payloadJson,
);

/// 读取歌曲详情（返回 `SongDetail` JSON）。
Future<String> getSongDetail({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiGetSongDetail(dbPath: dbPath, path: path);

/// 保存完整播放会话状态（写入内存 + SQLite）。
Future<void> savePlaybackSession({
  required String dbPath,
  required String sessionJson,
}) => RustLib.instance.api.crateApiSavePlaybackSession(
  dbPath: dbPath,
  sessionJson: sessionJson,
);

/// 从 SQLite 加载播放会话到内存，返回 `PlaybackSessionData` JSON。
Future<String> loadPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiLoadPlaybackSession(dbPath: dbPath);

/// 只读查询当前播放会话状态（读内存权威状态），返回 `PlaybackSessionData` JSON。
Future<String> sessionGetPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiSessionGetPlaybackSession(dbPath: dbPath);

/// 强制将当前播放会话内存状态持久化到 SQLite（定时刷新或退出时调用）。
Future<void> sessionFlushPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiSessionFlushPlaybackSession(dbPath: dbPath);

Future<void> updatePlaybackPosition({
  required String dbPath,
  required double positionSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiUpdatePlaybackPosition(
  dbPath: dbPath,
  positionSecs: positionSecs,
  isPlaying: isPlaying,
);

/// 预览批量重命名（返回 `RenamePreview[]` JSON）。
///
/// - `config_json`：[`RenameConfig`] 的 JSON（camelCase，含 `mode`/`template`/
///   `removeTrackPrefix`/`removeSourcePrefix`）
Future<String> previewRename({
  required String rootPath,
  required String configJson,
}) => RustLib.instance.api.crateApiPreviewRename(
  rootPath: rootPath,
  configJson: configJson,
);

/// 执行批量重命名（返回成功数）。
///
/// - `operations_json`：[`RenameOperation`] 数组的 JSON（camelCase，含 `originalPath`/`newName`）
Future<int> applyRename({required String operationsJson}) =>
    RustLib.instance.api.crateApiApplyRename(operationsJson: operationsJson);

/// 刷新指定文件夹歌曲（增量扫描并写库，返回该文件夹全部歌曲 JSON）。
Future<String> refreshFolderSongs({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiRefreshFolderSongs(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 根据歌曲信息构建下载文件名并解析非冲突完整路径（单次调用）。
Future<String> resolveDownloadFullPath({
  required String directory,
  required String title,
  required String artist,
  required String album,
  required String url,
  required String quality,
  required bool keepSourceFilename,
  required String fileNameStyle,
  required bool overwriteExisting,
}) => RustLib.instance.api.crateApiResolveDownloadFullPath(
  directory: directory,
  title: title,
  artist: artist,
  album: album,
  url: url,
  quality: quality,
  keepSourceFilename: keepSourceFilename,
  fileNameStyle: fileNameStyle,
  overwriteExisting: overwriteExisting,
);

/// 启动 USB 独占播放。返回设备名或错误信息。
/// `device_id` = AAudio 设备 ID（USB DAC），-1 = 默认设备。
/// `bit_perfect` = Bit-perfect 直出（绕过响度/EQ/音效/音量，按源位深整数直出）。
/// `dsd_native_passthrough` = DSD(.dsf/.dff) 原生 DoP 直通开关。
Future<String> startUsbExclusivePlayback({
  required String path,
  required int deviceId,
  required double volume,
  required double startTimeSecs,
  required bool isPlaying,
  required double volumeBalanceGain,
  required String equalizerSettingsJson,
  required String soundEffectSettingsJson,
  required bool bitPerfect,
  required bool dsdNativePassthrough,
  required bool sharedMode,
}) => RustLib.instance.api.crateApiStartUsbExclusivePlayback(
  path: path,
  deviceId: deviceId,
  volume: volume,
  startTimeSecs: startTimeSecs,
  isPlaying: isPlaying,
  volumeBalanceGain: volumeBalanceGain,
  equalizerSettingsJson: equalizerSettingsJson,
  soundEffectSettingsJson: soundEffectSettingsJson,
  bitPerfect: bitPerfect,
  dsdNativePassthrough: dsdNativePassthrough,
  sharedMode: sharedMode,
);

/// 停止 USB 独占播放并释放设备。
Future<void> stopUsbExclusivePlayback() =>
    RustLib.instance.api.crateApiStopUsbExclusivePlayback();

/// 暂停 USB 独占播放（保持进度，等待 resume 恢复）。
Future<void> pauseUsbExclusive() =>
    RustLib.instance.api.crateApiPauseUsbExclusive();

/// 从暂停恢复 USB 独占播放。
Future<void> resumeUsbExclusive() =>
    RustLib.instance.api.crateApiResumeUsbExclusive();

/// 跳转到指定位置（秒）。
Future<void> seekUsbExclusive({
  required double timeSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiSeekUsbExclusive(
  timeSecs: timeSecs,
  isPlaying: isPlaying,
);

/// 设置用户音量（0.0–1.0）。
Future<void> setUsbExclusiveVolume({required double volume}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveVolume(volume: volume);

/// 运行时更新独占管线的音量平衡（ReplayGain）目标增益（平滑渐变不断音）。
Future<void> setUsbExclusiveVolumeBalanceGain({required double gain}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveVolumeBalanceGain(gain: gain);

/// 更新 EQ 设置（camelCase JSON）。
Future<void> setUsbExclusiveEqualizer({required String settingsJson}) => RustLib
    .instance
    .api
    .crateApiSetUsbExclusiveEqualizer(settingsJson: settingsJson);

/// 更新音效设置（camelCase JSON）。
Future<void> setUsbExclusiveSoundEffect({required String settingsJson}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveSoundEffect(
      settingsJson: settingsJson,
    );

/// 运行时切换 Bit-perfect 直出：开启绕过响度/EQ/音效/音量，关闭恢复 DSP 链。
Future<void> setUsbExclusiveBitPerfect({required bool enabled}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveBitPerfect(enabled: enabled);

/// 当前独占播放是否处于 Bit-perfect 直出状态。
Future<bool> getUsbExclusiveBitPerfect() =>
    RustLib.instance.api.crateApiGetUsbExclusiveBitPerfect();

/// 查询当前独占播放输出设备/格式信息（JSON），用于前端展示已选输出设备。
Future<String> getUsbExclusiveDeviceInfo() =>
    RustLib.instance.api.crateApiGetUsbExclusiveDeviceInfo();

/// 获取当前播放位置（秒）。
Future<double> getUsbExclusivePositionSecs() =>
    RustLib.instance.api.crateApiGetUsbExclusivePositionSecs();

/// 下载在线歌曲真实音源直链到指定路径（流式写入 + QMC2 解密），返回最终路径。
///
/// - `headers_json`：可选 HTTP 头 JSON（对象）
/// - `ekey`：可选 QMC2 加密 key（base64）
Future<String> downloadOnlineSong({
  required String url,
  required String destPath,
  String? ekey,
  required String headersJson,
}) => RustLib.instance.api.crateApiDownloadOnlineSong(
  url: url,
  destPath: destPath,
  ekey: ekey,
  headersJson: headersJson,
);

/// 独立解密 QMC 加密文件（用户手动选择文件的工具入口）。
///
/// 支持三档策略：ekey 直供 / footer 自动提取 → QMC2；QMC1 老格式扩展名 → 固定密钥解密。
/// 解密成功后按内容修正扩展名。返回 JSON
/// `{"status":"decrypted"|"not_encrypted","outputPath":...,"renamedTo":...,"crypto":...}`。
Future<String> decryptQmcFileStandalone({
  required String filePath,
  String? ekey,
}) => RustLib.instance.api.crateApiDecryptQmcFileStandalone(
  filePath: filePath,
  ekey: ekey,
);

/// 下载后收尾编排：歌词保存 + 封面下载保存 + 元数据嵌入。
///
/// - `request_json`：[`FinalizeDownloadExtrasRequest`] 的 JSON（camelCase）
///
/// 返回 [`FinalizeDownloadExtrasResult`] JSON（camelCase）。
Future<String> finalizeDownloadExtras({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiFinalizeDownloadExtras(requestJson: requestJson);

/// 读取下载记录 JSON 文本（文件不存在或损坏时返回 `"{}"`）。
Future<String> readDownloadHistory({required String dataDir}) =>
    RustLib.instance.api.crateApiReadDownloadHistory(dataDir: dataDir);

/// 写入下载记录 JSON 文本（整体覆盖，自动创建父目录）。
Future<void> writeDownloadHistory({
  required String dataDir,
  required String content,
}) => RustLib.instance.api.crateApiWriteDownloadHistory(
  dataDir: dataDir,
  content: content,
);

/// 获取公告（返回解析出的 data JSON 字符串）。
Future<String> fetchAnnouncement() =>
    RustLib.instance.api.crateApiFetchAnnouncement();

/// 读取插件/文本文件内容（限 `.js/.json/.txt/.m3u/.m3u8`）。
Future<String> readPluginFile({required String path}) =>
    RustLib.instance.api.crateApiReadPluginFile(path: path);

/// 代理图片请求（自动添加 Referer，返回 data URL）。
Future<String> proxyImage({required String url, String? referer}) =>
    RustLib.instance.api.crateApiProxyImage(url: url, referer: referer);

/// 读取本地图片文件为 base64，返回 JSON `{"mime":..., "base64":...}`（分享封面上传用）。
Future<String> readImageBase64({required String path}) =>
    RustLib.instance.api.crateApiReadImageBase64(path: path);

/// 将插件解析得到的视频流式写入 `video-background` 缓存，返回缓存文件完整路径。
/// `cache_dir` 为应用缓存根目录（如 Flutter getApplicationCacheDirectory()）。
Future<String> downloadVideoToCache({
  required String cacheDir,
  required String url,
  Map<String, String>? headers,
}) => RustLib.instance.api.crateApiDownloadVideoToCache(
  cacheDir: cacheDir,
  url: url,
  headers: headers,
);

/// 清理本功能创建的后台视频缓存文件。
/// `cache_dir` 必须与下载时传入的缓存根目录一致。
Future<void> removeCachedBackgroundVideo({
  required String cacheDir,
  required String path,
}) => RustLib.instance.api.crateApiRemoveCachedBackgroundVideo(
  cacheDir: cacheDir,
  path: path,
);

/// QQ 音乐 zzcSign 签名。
Future<String> hostZzcSign({required String text}) =>
    RustLib.instance.api.crateApiHostZzcSign(text: text);

/// 酷狗参数签名（`platform` 为 `"web"` 用 web 盐，其余用 android 盐）。
Future<String> hostKugouSign({
  required String params,
  required String platform,
  String? body,
}) => RustLib.instance.api.crateApiHostKugouSign(
  params: params,
  platform: platform,
  body: body,
);

/// 酷狗请求密钥（android 盐）。
Future<String> hostKugouRequestKey() =>
    RustLib.instance.api.crateApiHostKugouRequestKey();

/// 咪咕搜索签名。返回 JSON `{"sign":..., "deviceId":...}`。
Future<String> hostMiguSign({required String text, required String time}) =>
    RustLib.instance.api.crateApiHostMiguSign(text: text, time: time);

/// 网易云 linuxapi 加密（AES-128-ECB PKCS7 → hex 大写）。
Future<String> hostLinuxapiEncrypt({required String payload}) =>
    RustLib.instance.api.crateApiHostLinuxapiEncrypt(payload: payload);

/// 网易云 weapi 加密。返回 JSON `{"params":..., "encSecKey":...}`。
Future<String> hostWeapiEncrypt({required String payload}) =>
    RustLib.instance.api.crateApiHostWeapiEncrypt(payload: payload);

/// 通用 SHA-256 hex（插件脚本哈希等）。
Future<String> hostSha256Hex({required String text}) =>
    RustLib.instance.api.crateApiHostSha256Hex(text: text);

/// 校验服务端下发的兜底模块签名（ed25519）。返回 true 表示签名有效可执行。
Future<bool> verifyFallbackModuleSignature({
  required String moduleKey,
  required PlatformInt64 version,
  required String code,
  required String signature,
}) => RustLib.instance.api.crateApiVerifyFallbackModuleSignature(
  moduleKey: moduleKey,
  version: version,
  code: code,
  signature: signature,
);

/// 初始化全局插件引擎（首次调用时以 `data_dir` 建立 Cookie/Storage 存储）。
Future<void> pluginEngineInit({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineInit(dataDir: dataDir);

/// 加载 LX 格式插件，返回 `EngineLoadResult` JSON（`ok`/`error`/`metadata`/`logs`）。
Future<String> pluginEngineLoadLx({
  required String dataDir,
  required String pluginId,
  required String script,
  required String scriptInfoJson,
}) => RustLib.instance.api.crateApiPluginEngineLoadLx(
  dataDir: dataDir,
  pluginId: pluginId,
  script: script,
  scriptInfoJson: scriptInfoJson,
);

/// 加载 MusicFree 格式插件，返回 `EngineLoadResult` JSON。
Future<String> pluginEngineLoadMusicfree({
  required String dataDir,
  required String pluginId,
  required String script,
  required String userVarsJson,
}) => RustLib.instance.api.crateApiPluginEngineLoadMusicfree(
  dataDir: dataDir,
  pluginId: pluginId,
  script: script,
  userVarsJson: userVarsJson,
);

/// 调用插件方法，返回 `EngineCallResult` JSON（`ok`/`error`/`data`/`logs`）。
Future<String> pluginEngineCall({
  required String dataDir,
  required String pluginId,
  required String method,
  required String argsJson,
  String? userVarsJson,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiPluginEngineCall(
  dataDir: dataDir,
  pluginId: pluginId,
  method: method,
  argsJson: argsJson,
  userVarsJson: userVarsJson,
  timeoutMs: timeoutMs,
);

/// 销毁指定插件的沙箱实例。
Future<void> pluginEngineDestroy({
  required String dataDir,
  required String pluginId,
}) => RustLib.instance.api.crateApiPluginEngineDestroy(
  dataDir: dataDir,
  pluginId: pluginId,
);

/// 销毁全部插件沙箱实例。
Future<void> pluginEngineDestroyAll({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineDestroyAll(dataDir: dataDir);

/// 取消正在进行的音频识别。
Future<void> cancelRecognizeSystemAudio() =>
    RustLib.instance.api.crateApiCancelRecognizeSystemAudio();

/// 使用自定义 PCM 数据识别歌曲（8000Hz/16bit/单声道），返回 `RecognizeResponse` JSON。
Future<String> recognizeWithPcm({required List<int> pcm}) =>
    RustLib.instance.api.crateApiRecognizeWithPcm(pcm: pcm);

/// 设置在线播放缓存上限（字节）。
Future<void> setStreamCacheMaxSizeBytes({required BigInt bytes}) =>
    RustLib.instance.api.crateApiSetStreamCacheMaxSizeBytes(bytes: bytes);

/// 当前在线播放缓存占用（字节）。
Future<BigInt> streamCacheCurrentBytes() =>
    RustLib.instance.api.crateApiStreamCacheCurrentBytes();

/// 在线播放缓存上限（字节）。
Future<BigInt> streamCacheMaxBytes() =>
    RustLib.instance.api.crateApiStreamCacheMaxBytes();

/// 清空在线播放缓存。
Future<void> clearStreamCache() =>
    RustLib.instance.api.crateApiClearStreamCache();

/// 读取音质分布（返回 [`QualityDistribution`] JSON）。
Future<String> statsGetQualityDistribution({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetQualityDistribution(dbPath: dbPath);

/// 读取格式分布（返回 [`FormatDistribution`] JSON）。
Future<String> statsGetFormatDistribution({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetFormatDistribution(dbPath: dbPath);

/// 读取曲库统计（歌曲/歌手/专辑数等，返回 [`LibraryStats`] JSON）。
Future<String> statsGetLibraryStats({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetLibraryStats(dbPath: dbPath);

/// 重置本地听歌统计（清空播放计数/时长等，不清收藏与下载）。
Future<void> statsResetLocalStatistics({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsResetLocalStatistics(dbPath: dbPath);

/// 收藏歌手目录：`favorite_paths` 为收藏的歌曲路径数组。
/// 返回 [`ArtistCatalogItem[]`] JSON。
Future<String> statsGetFavoriteArtistCatalog({
  required String dbPath,
  required List<String> favoritePaths,
}) => RustLib.instance.api.crateApiStatsGetFavoriteArtistCatalog(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
);

/// 收藏专辑目录：`favorite_paths` 为收藏的歌曲路径数组。
/// 返回 [`AlbumCatalogItem[]`] JSON。
Future<String> statsGetFavoriteAlbumCatalog({
  required String dbPath,
  required List<String> favoritePaths,
}) => RustLib.instance.api.crateApiStatsGetFavoriteAlbumCatalog(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
);

/// 收藏歌曲路径视图：`favorite_paths` 为收藏的歌曲路径数组。
/// 返回排序过滤后的 `String[]`（歌曲路径）。`sort_mode` 为 [`SongPathSortMode`] 的 snake_case 字符串。
Future<String> statsGetFavoriteSongPathsView({
  required String dbPath,
  required List<String> favoritePaths,
  String? query,
  required String sortMode,
  String? detailFilterType,
  String? detailFilterValue,
}) => RustLib.instance.api.crateApiStatsGetFavoriteSongPathsView(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
  query: query,
  sortMode: sortMode,
  detailFilterType: detailFilterType,
  detailFilterValue: detailFilterValue,
);

/// 近期专辑目录：`recent_entries_json` 为 [`RecentHistoryImportEntry[]`] 的 camelCase JSON。
/// 返回 [`RecentAlbumCatalogItem[]`] JSON。
Future<String> statsGetRecentAlbumCatalog({
  required String dbPath,
  required String recentEntriesJson,
}) => RustLib.instance.api.crateApiStatsGetRecentAlbumCatalog(
  dbPath: dbPath,
  recentEntriesJson: recentEntriesJson,
);

/// 近期歌曲路径视图：`recent_entries_json` 为 [`RecentHistoryImportEntry[]`] 的 camelCase JSON。
/// 返回排序过滤后的 `String[]`。
Future<String> statsGetRecentSongPathsView({
  required String dbPath,
  required String recentEntriesJson,
  String? query,
  required String sortMode,
}) => RustLib.instance.api.crateApiStatsGetRecentSongPathsView(
  dbPath: dbPath,
  recentEntriesJson: recentEntriesJson,
  query: query,
  sortMode: sortMode,
);

/// 近期歌单目录：`playlists_json` 为 [`PlaylistImportItem[]`] 的 camelCase JSON，
/// `recent_entries_json` 为 [`RecentHistoryImportEntry[]`] 的 camelCase JSON。
/// 返回 [`RecentPlaylistCatalogItem[]`] JSON。
Future<String> statsGetRecentPlaylistCatalog({
  required String playlistsJson,
  required String recentEntriesJson,
}) => RustLib.instance.api.crateApiStatsGetRecentPlaylistCatalog(
  playlistsJson: playlistsJson,
  recentEntriesJson: recentEntriesJson,
);

/// 清空封面缓存目录，并同步清空无图负缓存（释放「提取失败」记忆，允许立即重试）。
Future<void> clearCoverCache({required String cacheDir}) =>
    RustLib.instance.api.crateApiClearCoverCache(cacheDir: cacheDir);

/// 获取 LX 音乐源封面 URL。`song_info_json` 为 [`LxUrlSongInfo`] 的 camelCase JSON。
Future<String> getLxCover({required String songInfoJson}) =>
    RustLib.instance.api.crateApiGetLxCover(songInfoJson: songInfoJson);

/// 清除 LX 音源 URL 直链缓存。
Future<void> clearLxUrlCache() =>
    RustLib.instance.api.crateApiClearLxUrlCache();

/// 清除 LX 音源全部缓存（URL 直链 + 搜索结果）。
Future<void> clearLxAllCache() =>
    RustLib.instance.api.crateApiClearLxAllCache();

/// 查找替代落雪音源（换源匹配，双端通用，对齐桌面端 find_alternative_lx_source）。
///
/// - `failed_sources_json`：已失败音源数组 JSON（如 `["kw","tx"]`）。
///
/// 返回 [`crate::music::url_resolver::AlternativeSourceResult`] 的 camelCase JSON；
/// 无匹配时返回 `"null"`。URL 解析由 Dart 插件编排层完成。
Future<String> findAlternativeLxSource({
  required String songName,
  required String songArtist,
  required double songDuration,
  required String failedSourcesJson,
}) => RustLib.instance.api.crateApiFindAlternativeLxSource(
  songName: songName,
  songArtist: songArtist,
  songDuration: songDuration,
  failedSourcesJson: failedSourcesJson,
);

/// 测试远程源连通性。`source_json` 为 [`RemoteSourceInput`] 的 camelCase JSON。
/// 返回 `{"ok":bool,"message":String}` JSON。
Future<String> testRemoteSource({required String sourceJson}) =>
    RustLib.instance.api.crateApiTestRemoteSource(sourceJson: sourceJson);

/// 预缓存远程歌曲到本地缓存（`remote_uri` 形如 `remote://<source_id>/<path>`）。
Future<void> precacheRemoteSong({
  required String dbPath,
  required String cacheRoot,
  required String remoteUri,
}) => RustLib.instance.api.crateApiPrecacheRemoteSong(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  remoteUri: remoteUri,
);

/// 列出远程源指定目录下的条目（返回 [`RemoteFileEntry[]`] JSON）。
Future<String> listRemoteDirectory({
  required String dbPath,
  required String sourceId,
  required String path,
}) => RustLib.instance.api.crateApiListRemoteDirectory(
  dbPath: dbPath,
  sourceId: sourceId,
  path: path,
);

/// 将 ExoPlayer 不支持的音频转换为可播放的缓存文件（远程源 `remote://` 自动先下载缓存）。
/// 处理范围：APE/WV → 解码 WAV；AIFF → 解码 WAV；QMC 加密 → 解密为内部格式。
/// 其余格式原样返回源路径。
/// 返回 JSON：{path: 可播放路径, decodedNow: 本次是否实际执行转换}。
Future<String> transcodeAudioToWav({
  required String dbPath,
  required String cacheRoot,
  required String srcPath,
}) => RustLib.instance.api.crateApiTranscodeAudioToWav(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  srcPath: srcPath,
);

/// 用 `Range: bytes=0-0` 探测直链文件大小（返回 [`ProbeUrlInfo`] JSON）。
Future<String> probeUrlSize({required String url}) =>
    RustLib.instance.api.crateApiProbeUrlSize(url: url);

/// 写入文本文件（自动创建父目录），返回目标路径。
Future<String> writeTextFile({
  required String content,
  required String destPath,
}) => RustLib.instance.api.crateApiWriteTextFile(
  content: content,
  destPath: destPath,
);

/// 下载图片二进制（绕过 WebView CORS），返回 `{"data":String,"mime":String}` JSON（data 为 base64）。
Future<String> fetchImageBytes({required String url}) =>
    RustLib.instance.api.crateApiFetchImageBytes(url: url);

/// 将歌曲元数据写入音频文件 tag。`request_json` 为 [`EmbedMetadataRequest`] 的 camelCase JSON。
Future<void> embedAudioMetadata({required String requestJson}) =>
    RustLib.instance.api.crateApiEmbedAudioMetadata(requestJson: requestJson);

/// 判断路径是否为目录。
Future<bool> isDirectory({required String path}) =>
    RustLib.instance.api.crateApiIsDirectory(path: path);

/// 保存歌手头像到封面目录，并可选写入该歌手所有歌曲标签。
/// 返回头像路径（`save_artist_avatar_response.avatar_path` 的 JSON 字符串）。
Future<String> saveArtistAvatar({
  required String dbPath,
  required String coversRoot,
  required PlatformInt64 artistId,
  required String imagePath,
  required bool writeToTags,
}) => RustLib.instance.api.crateApiSaveArtistAvatar(
  dbPath: dbPath,
  coversRoot: coversRoot,
  artistId: artistId,
  imagePath: imagePath,
  writeToTags: writeToTags,
);

/// 音乐库「全部歌曲」视图（支持查询过滤、歌手/专辑过滤、排序），返回 `String[]` 路径。
Future<String> getLibrarySongPathsForAllView({
  required String dbPath,
  String? query,
  String? artistFilter,
  String? albumFilter,
  required String sortMode,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsForAllView(
  dbPath: dbPath,
  query: query,
  artistFilter: artistFilter,
  albumFilter: albumFilter,
  sortMode: sortMode,
);

/// 扫描音乐库下所有已添加文件夹，返回全部 `LibrarySong[]`。
Future<String> scanLibrary({
  required String dbPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiScanLibrary(
  dbPath: dbPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 获取文件夹的直接子目录节点（返回 `FolderNode[]`）。
Future<String> getFolderChildren({
  required String dbPath,
  required String folderPath,
}) => RustLib.instance.api.crateApiGetFolderChildren(
  dbPath: dbPath,
  folderPath: folderPath,
);

/// 递归查找某文件夹下的第一首歌曲路径（用于文件夹视图预览）。
Future<String> getFolderFirstSong({
  required String dbPath,
  required String folderPath,
}) => RustLib.instance.api.crateApiGetFolderFirstSong(
  dbPath: dbPath,
  folderPath: folderPath,
);

/// 在父目录下创建新文件夹，返回新文件夹路径。
Future<String> createFolder({
  required String parentPath,
  required String folderName,
}) => RustLib.instance.api.crateApiCreateFolder(
  parentPath: parentPath,
  folderName: folderName,
);

/// 删除文件夹（递归删除目录下所有内容）。注意：真删，不会进回收站。
Future<void> deleteFolder({required String path}) =>
    RustLib.instance.api.crateApiDeleteFolder(path: path);

/// 移动文件到目标文件夹（同步数据库中的歌曲路径）。
Future<void> moveFileToFolder({
  required String dbPath,
  required String sourcePath,
  required String targetFolder,
}) => RustLib.instance.api.crateApiMoveFileToFolder(
  dbPath: dbPath,
  sourcePath: sourcePath,
  targetFolder: targetFolder,
);

/// 批量移动音乐文件到目标文件夹（返回 `BatchMoveMusicFilesResult` JSON）。
Future<String> batchMoveMusicFiles({
  required String dbPath,
  required List<String> paths,
  required String targetFolder,
}) => RustLib.instance.api.crateApiBatchMoveMusicFiles(
  dbPath: dbPath,
  paths: paths,
  targetFolder: targetFolder,
);

/// 移动单个音乐文件到新路径（同步数据库路径）。
Future<void> moveMusicFile({
  required String dbPath,
  required String oldPath,
  required String newPath,
}) => RustLib.instance.api.crateApiMoveMusicFile(
  dbPath: dbPath,
  oldPath: oldPath,
  newPath: newPath,
);

/// 删除音乐文件（真删，不回收）。
Future<void> deleteMusicFile({required String path}) =>
    RustLib.instance.api.crateApiDeleteMusicFile(path: path);

/// 从最近播放历史与统计中批量移除歌曲。
Future<void> removeSongsFromHistoryAndStatistics({
  required String dbPath,
  required List<String> songPaths,
}) => RustLib.instance.api.crateApiRemoveSongsFromHistoryAndStatistics(
  dbPath: dbPath,
  songPaths: songPaths,
);

/// 解析下载目标路径：目录 + 文件名，`overwrite_existing` 为 false 时自动追加 `(1)`/`(2)` 避免冲突。
Future<String> resolveDownloadPath({
  required String directory,
  required String fileName,
  required bool overwriteExisting,
}) => RustLib.instance.api.crateApiResolveDownloadPath(
  directory: directory,
  fileName: fileName,
  overwriteExisting: overwriteExisting,
);

/// 按命名风格构建下载文件基名（不含扩展名）。
Future<String> buildDownloadBasename({
  required String title,
  required String artist,
  required String album,
  required String fileNameStyle,
}) => RustLib.instance.api.crateApiBuildDownloadBasename(
  title: title,
  artist: artist,
  album: album,
  fileNameStyle: fileNameStyle,
);

/// 写入原始下载字节到目标路径（创建父目录），返回目标路径。
Future<String> saveDownloadBytes({
  required List<int> data,
  required String destPath,
}) => RustLib.instance.api.crateApiSaveDownloadBytes(
  data: data,
  destPath: destPath,
);

/// 保存下载歌词文本到目标路径（创建父目录），返回目标路径。
Future<String> saveDownloadLyrics({
  required String content,
  required String destPath,
}) => RustLib.instance.api.crateApiSaveDownloadLyrics(
  content: content,
  destPath: destPath,
);

/// 获取流缓存信息，返回 `{"current":u64,"max":u64}` JSON。
Future<String> getStreamCacheInfo() =>
    RustLib.instance.api.crateApiGetStreamCacheInfo();

/// 判断某个 URL 是否已缓存完整。
Future<bool> isStreamCached({required String url}) =>
    RustLib.instance.api.crateApiIsStreamCached(url: url);

/// 将已缓存的 URL 文件复制到目标路径，返回实际写入字节数。
Future<BigInt> copyStreamCache({
  required String url,
  required String destPath,
}) =>
    RustLib.instance.api.crateApiCopyStreamCache(url: url, destPath: destPath);

/// 等待某个 URL 缓存下载完成（超时秒数），完成返回 true。
Future<bool> waitStreamComplete({
  required String url,
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiWaitStreamComplete(
  url: url,
  timeoutSecs: timeoutSecs,
);

/// 在播放前评估/更新响度元数据并计算目标线性增益。
/// `enabled` 为 true 时按 `gain_offset_db`（dB）与 `prevent_clipping` 计算，
/// 返回 `ProcessLoudnessResult` JSON；`enabled` 为 false 时返回 1.0（原始音量）。
Future<String> updateLoudnessSettings({
  required String dbPath,
  required bool enabled,
  PlatformInt64? songId,
  String? songPath,
  required double gainOffsetDb,
  required bool preventClipping,
}) => RustLib.instance.api.crateApiUpdateLoudnessSettings(
  dbPath: dbPath,
  enabled: enabled,
  songId: songId,
  songPath: songPath,
  gainOffsetDb: gainOffsetDb,
  preventClipping: preventClipping,
);

/// 将云端累计总听歌时长合并进本地（取较大值），返回 [`CloudMergeResult`] JSON。
Future<String> mergeCloudListenDuration({
  required String dbPath,
  required PlatformInt64 totalSeconds,
}) => RustLib.instance.api.crateApiMergeCloudListenDuration(
  dbPath: dbPath,
  totalSeconds: totalSeconds,
);

/// 导出全局 + 每日听歌统计快照（JSON），用于上传服务端跨设备同步。
Future<String> statsExportListenSnapshot({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsExportListenSnapshot(dbPath: dbPath);

/// 导入（MAX 合并）服务端听歌统计快照（JSON），返回 [`ListenStatsSyncResult`] JSON。
Future<String> statsImportListenSnapshot({
  required String dbPath,
  required String snapshotJson,
}) => RustLib.instance.api.crateApiStatsImportListenSnapshot(
  dbPath: dbPath,
  snapshotJson: snapshotJson,
);

/// 导入（累加合并）服务端听歌统计快照（JSON），返回 [`ListenStatsSyncResult`] JSON。
Future<String> statsImportListenSnapshotAdd({
  required String dbPath,
  required String snapshotJson,
}) => RustLib.instance.api.crateApiStatsImportListenSnapshotAdd(
  dbPath: dbPath,
  snapshotJson: snapshotJson,
);

/// 清零本地累计 + 每日听歌统计（服务端后台清零后下发）。
Future<void> statsClearListenStats({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsClearListenStats(dbPath: dbPath);

/// 导入插件引擎店铺会话（cookie + storage）。默认仅补缺不覆盖；payload 可选
/// `overwriteCookies: true` 时改为覆盖式写入 cookie（用户变量显式同步场景）。
Future<void> pluginEngineStoreImport({
  required String dataDir,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginEngineStoreImport(
  dataDir: dataDir,
  payloadJson: payloadJson,
);

/// 获取某个域名的 cookie header（分号分隔的 `name=value` 字符串）。
Future<String> pluginEngineCookieHeaderForDomain({
  required String dataDir,
  required String domain,
}) => RustLib.instance.api.crateApiPluginEngineCookieHeaderForDomain(
  dataDir: dataDir,
  domain: domain,
);

/// 获取插件引擎会话快照，返回 `{"cookies":..., "storage":...}` JSON。
Future<String> pluginEngineStoreSnapshot({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineStoreSnapshot(dataDir: dataDir);

/// 搜索局域网 DLNA 渲染器，返回 `Vec<DlnaDevice>` JSON。
Future<String> dlnaSearchDevices({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiDlnaSearchDevices(timeoutMs: timeoutMs);

/// 投递媒体到渲染器（SetAVTransportURI），返回 `CastMediaInfo` JSON（含续投 token）。
Future<String> dlnaCastSetUri({
  required String deviceJson,
  required String mediaJson,
  String? coverJson,
  required String title,
  required String artist,
  required String album,
  required BigInt durationMs,
}) => RustLib.instance.api.crateApiDlnaCastSetUri(
  deviceJson: deviceJson,
  mediaJson: mediaJson,
  coverJson: coverJson,
  title: title,
  artist: artist,
  album: album,
  durationMs: durationMs,
);

Future<void> dlnaCastPlay({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastPlay(deviceJson: deviceJson);

Future<void> dlnaCastPause({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastPause(deviceJson: deviceJson);

Future<void> dlnaCastStop({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastStop(deviceJson: deviceJson);

Future<void> dlnaCastSeek({required String deviceJson, required double secs}) =>
    RustLib.instance.api.crateApiDlnaCastSeek(
      deviceJson: deviceJson,
      secs: secs,
    );

Future<void> dlnaCastSetVolume({
  required String deviceJson,
  required int percent,
}) => RustLib.instance.api.crateApiDlnaCastSetVolume(
  deviceJson: deviceJson,
  percent: percent,
);

/// 查询渲染器传输状态，返回 `CastTransportState` JSON。
Future<String> dlnaCastGetState({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastGetState(deviceJson: deviceJson);

/// TTL 续投：热替换 token 上游（电视不断流）。
Future<bool> dlnaUpdateMediaToken({
  required String token,
  required String payloadJson,
}) => RustLib.instance.api.crateApiDlnaUpdateMediaToken(
  token: token,
  payloadJson: payloadJson,
);

/// 启用本机渲染器（SSDP 广播 + SOAP 端点），返回实际端口。
Future<int> dlnaEnableRenderer({
  required String friendlyName,
  required String udn,
}) => RustLib.instance.api.crateApiDlnaEnableRenderer(
  friendlyName: friendlyName,
  udn: udn,
);

Future<void> dlnaDisableRenderer() =>
    RustLib.instance.api.crateApiDlnaDisableRenderer();

/// 渲染器状态，返回 `{"running":bool,"friendlyName":String,"port":u16}` JSON。
Future<String> dlnaRendererStatus() =>
    RustLib.instance.api.crateApiDlnaRendererStatus();

/// 长轮询下一条 DMR 指令（超时返回 None），返回 `DmrCommand` JSON。
Future<String?> dlnaDmrNextCommand({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiDlnaDmrNextCommand(timeoutMs: timeoutMs);

/// Dart 侧上报播放快照（供 DMR SOAP 状态应答）。
///
/// `state` ∈ "playing" / "paused" / "stopped" / "no_media" / "transitioning"。
Future<void> dlnaDmrReportPlayback({
  required String state,
  required double positionSecs,
  required double durationSecs,
  required int volumePercent,
  required bool muted,
}) => RustLib.instance.api.crateApiDlnaDmrReportPlayback(
  state: state,
  positionSecs: positionSecs,
  durationSecs: durationSecs,
  volumePercent: volumePercent,
  muted: muted,
);

/// 批量音频格式转换入口。
/// `options_json` 格式：`{"targetFormat":"wav"|"flac", "sampleRate": null|u32}`
/// 返回 `ConvertResult[]` JSON，每项含 inputPath / outputPath / success / error / durationSecs。
Future<String> convertAudioBatch({
  required List<String> inputPaths,
  required String outDir,
  required String optionsJson,
}) => RustLib.instance.api.crateApiConvertAudioBatch(
  inputPaths: inputPaths,
  outDir: outDir,
  optionsJson: optionsJson,
);

/// 查询输入文件是否可被本模块解码。
Future<List<String>> audioConvertSupportedInputs() =>
    RustLib.instance.api.crateApiAudioConvertSupportedInputs();

/// 本模块支持的目标输出格式。
Future<List<String>> audioConvertSupportedOutputs() =>
    RustLib.instance.api.crateApiAudioConvertSupportedOutputs();

/// 已保存远程源的表单覆盖项（编辑时密码留空则沿用存储密码）。
class WebdavSourceOverrides {
  final String? baseUrl;
  final String? username;
  final String? rootPath;

  const WebdavSourceOverrides({this.baseUrl, this.username, this.rootPath});

  static Future<WebdavSourceOverrides> default_() =>
      RustLib.instance.api.crateApiWebdavSourceOverridesDefault();

  @override
  int get hashCode => baseUrl.hashCode ^ username.hashCode ^ rootPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebdavSourceOverrides &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          username == other.username &&
          rootPath == other.rootPath;
}
