// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'music/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_cover_cache_dir`, `global_playback_session`, `open_scan_conn`, `open_stats_conn`, `parse_device`, `parse_media`, `parse_remote_source`, `stats_schema_ready`

Future<String> parseLyrics({required String rawLyrics}) =>
    RustLib.instance.api.crateApiParseLyrics(rawLyrics: rawLyrics);

Future<String> lxSearch({
  required String source,
  required String keyword,
  required int limit,
}) => RustLib.instance.api.crateApiLxSearch(
  source: source,
  keyword: keyword,
  limit: limit,
);

Future<String> txSearchAlbums({
  required String keyword,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiTxSearchAlbums(
  keyword: keyword,
  page: page,
  limit: limit,
);

Future<String> txAlbumSongs({
  required String albumMid,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiTxAlbumSongs(
  albumMid: albumMid,
  page: page,
  limit: limit,
);

Future<String> txBatchTrackInterval({required String songIdsJson}) =>
    RustLib.instance.api.crateApiTxBatchTrackInterval(songIdsJson: songIdsJson);

Future<String> lxSearchPlaylists({
  required String source,
  required String keyword,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiLxSearchPlaylists(
  source: source,
  keyword: keyword,
  page: page,
  limit: limit,
);

Future<String> lxPlaylistTracks({
  required String source,
  required String playlistId,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiLxPlaylistTracks(
  source: source,
  playlistId: playlistId,
  page: page,
  limit: limit,
);

Future<String> lxAlbumSongs({
  required String source,
  required String albumId,
  required int page,
  required int limit,
}) => RustLib.instance.api.crateApiLxAlbumSongs(
  source: source,
  albumId: albumId,
  page: page,
  limit: limit,
);

Future<String> fetchLyricFromSource({
  required String source,
  required String songInfoJson,
}) => RustLib.instance.api.crateApiFetchLyricFromSource(
  source: source,
  songInfoJson: songInfoJson,
);

Future<void> webdavTestConnection({required String sourceJson}) =>
    RustLib.instance.api.crateApiWebdavTestConnection(sourceJson: sourceJson);

Future<String> webdavBrowseDirectory({
  required String sourceJson,
  required String path,
}) => RustLib.instance.api.crateApiWebdavBrowseDirectory(
  sourceJson: sourceJson,
  path: path,
);

Future<void> webdavTestSavedSource({
  required String dbPath,
  required String sourceId,
  required String overridesJson,
}) => RustLib.instance.api.crateApiWebdavTestSavedSource(
  dbPath: dbPath,
  sourceId: sourceId,
  overridesJson: overridesJson,
);

Future<double> loudnessPlaybackGainForFile({
  required String filePath,
  required double gainOffsetDb,
  required bool preventClipping,
}) => RustLib.instance.api.crateApiLoudnessPlaybackGainForFile(
  filePath: filePath,
  gainOffsetDb: gainOffsetDb,
  preventClipping: preventClipping,
);

Future<String> getTrackLoudnessInfo({
  required String dbPath,
  required PlatformInt64 songId,
}) => RustLib.instance.api.crateApiGetTrackLoudnessInfo(
  dbPath: dbPath,
  songId: songId,
);

Future<void> statsRecordPlay({
  required String dbPath,
  required String payloadJson,
}) => RustLib.instance.api.crateApiStatsRecordPlay(
  dbPath: dbPath,
  payloadJson: payloadJson,
);

Future<String> statsGetListenDurations({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetListenDurations(dbPath: dbPath);

Future<String> statsGetBehaviorStats({
  required String dbPath,
  required String timeRangeJson,
}) => RustLib.instance.api.crateApiStatsGetBehaviorStats(
  dbPath: dbPath,
  timeRangeJson: timeRangeJson,
);

Future<String> statsGetRecentHistory({required String dbPath, BigInt? limit}) =>
    RustLib.instance.api.crateApiStatsGetRecentHistory(
      dbPath: dbPath,
      limit: limit,
    );

Future<void> statsAddToHistory({
  required String dbPath,
  required String songPath,
}) => RustLib.instance.api.crateApiStatsAddToHistory(
  dbPath: dbPath,
  songPath: songPath,
);

Future<void> statsClearRecentHistory({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsClearRecentHistory(dbPath: dbPath);

Future<void> statsRemoveFromRecentHistory({
  required String dbPath,
  required List<String> songPaths,
}) => RustLib.instance.api.crateApiStatsRemoveFromRecentHistory(
  dbPath: dbPath,
  songPaths: songPaths,
);

Future<String> statsExportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsExportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

Future<String> statsPreviewStatisticsImport({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsPreviewStatisticsImport(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

Future<String> statsImportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsImportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

Future<String> scanMusicFolder({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
  List<String>? allowedFormats,
}) => RustLib.instance.api.crateApiScanMusicFolder(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
  allowedFormats: allowedFormats,
);

Future<String> parseAudioFiles({
  required List<String> paths,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiParseAudioFiles(
  paths: paths,
  minimumDurationSeconds: minimumDurationSeconds,
);

Future<String> parseMusicFolder({
  required String folderPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiParseMusicFolder(
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

Future<String> parseAudioFromFdAndroid({
  required int fd,
  required String fileName,
  required String pathKey,
  required String format,
}) => RustLib.instance.api.crateApiParseAudioFromFdAndroid(
  fd: fd,
  fileName: fileName,
  pathKey: pathKey,
  format: format,
);

Future<String> parseAudioFromPathAndroid({
  required String filePath,
  required String fileName,
  required String pathKey,
  required String format,
}) => RustLib.instance.api.crateApiParseAudioFromPathAndroid(
  filePath: filePath,
  fileName: fileName,
  pathKey: pathKey,
  format: format,
);

Future<String> extractSongCoverThumbnailFromPath({
  required String cacheRoot,
  required String sourceKey,
  required String realPath,
}) => RustLib.instance.api.crateApiExtractSongCoverThumbnailFromPath(
  cacheRoot: cacheRoot,
  sourceKey: sourceKey,
  realPath: realPath,
);

Future<String> scanSafSongsCommit({
  required String dbPath,
  required String folderKey,
  required String songsJson,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiScanSafSongsCommit(
  dbPath: dbPath,
  folderKey: folderKey,
  songsJson: songsJson,
  minimumDurationSeconds: minimumDurationSeconds,
);

Future<String> listRemoteSources({required String dbPath}) =>
    RustLib.instance.api.crateApiListRemoteSources(dbPath: dbPath);

Future<String> saveRemoteSource({
  required String dbPath,
  required String sourceJson,
}) => RustLib.instance.api.crateApiSaveRemoteSource(
  dbPath: dbPath,
  sourceJson: sourceJson,
);

Future<void> removeRemoteSource({
  required String dbPath,
  required String sourceId,
}) => RustLib.instance.api.crateApiRemoveRemoteSource(
  dbPath: dbPath,
  sourceId: sourceId,
);

Future<String> syncRemoteSource({
  required String dbPath,
  required String cacheRoot,
  required String sourceId,
}) => RustLib.instance.api.crateApiSyncRemoteSource(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  sourceId: sourceId,
);

Future<String> getRemoteCacheUsage({required String cacheRoot}) =>
    RustLib.instance.api.crateApiGetRemoteCacheUsage(cacheRoot: cacheRoot);

Future<String> clearRemoteCache({required String cacheRoot}) =>
    RustLib.instance.api.crateApiClearRemoteCache(cacheRoot: cacheRoot);

Future<String> remotePlaybackSource({
  required String dbPath,
  required String remoteUri,
}) => RustLib.instance.api.crateApiRemotePlaybackSource(
  dbPath: dbPath,
  remoteUri: remoteUri,
);

Future<String> authAuthedRequest({
  required String dataDir,
  required String action,
  required String bodyJson,
  BigInt? fetchTimeoutMs,
}) => RustLib.instance.api.crateApiAuthAuthedRequest(
  dataDir: dataDir,
  action: action,
  bodyJson: bodyJson,
  fetchTimeoutMs: fetchTimeoutMs,
);

Future<void> authSaveCredentials({
  required String dataDir,
  required String token,
  required String userJson,
}) => RustLib.instance.api.crateApiAuthSaveCredentials(
  dataDir: dataDir,
  token: token,
  userJson: userJson,
);

Future<String> authGetCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthGetCredentials(dataDir: dataDir);

Future<void> authClearCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthClearCredentials(dataDir: dataDir);

Future<void> authSetBaseUrl({
  required String dataDir,
  required String baseUrl,
}) => RustLib.instance.api.crateApiAuthSetBaseUrl(
  dataDir: dataDir,
  baseUrl: baseUrl,
);

Future<void> authSetApiSecret({
  required String dataDir,
  required String apiSecret,
}) => RustLib.instance.api.crateApiAuthSetApiSecret(
  dataDir: dataDir,
  apiSecret: apiSecret,
);

Future<String> getLibraryFolders({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryFolders(dbPath: dbPath);

Future<void> addLibraryFolder({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiAddLibraryFolder(dbPath: dbPath, path: path);

Future<void> removeLibraryFolder({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiRemoveLibraryFolder(
  dbPath: dbPath,
  path: path,
);

Future<String> getLibrarySongsCached({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibrarySongsCached(dbPath: dbPath);

Future<String> getLibrarySongsByPaths({
  required String dbPath,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGetLibrarySongsByPaths(
  dbPath: dbPath,
  paths: paths,
);

Future<String> searchLibrarySongs({
  required String dbPath,
  required String query,
  BigInt? limit,
}) => RustLib.instance.api.crateApiSearchLibrarySongs(
  dbPath: dbPath,
  query: query,
  limit: limit,
);

Future<String> getLibraryArtistCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryArtistCatalog(dbPath: dbPath);

Future<String> getLibraryAlbumCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryAlbumCatalog(dbPath: dbPath);

Future<String> getLibrarySongPathsByArtist({
  required String dbPath,
  required String artistName,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByArtist(
  dbPath: dbPath,
  artistName: artistName,
);

Future<String> getLibrarySongPathsByAlbum({
  required String dbPath,
  required String albumKey,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByAlbum(
  dbPath: dbPath,
  albumKey: albumKey,
);

Future<String> getLibrarySongPathsForFolderView({
  required String dbPath,
  required String folderPath,
  String? query,
  required String sortMode,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsForFolderView(
  dbPath: dbPath,
  folderPath: folderPath,
  query: query,
  sortMode: sortMode,
);

Future<String> getLibraryHierarchy({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryHierarchy(dbPath: dbPath);

Future<String> getSongCoverThumbnail({
  required String dbPath,
  required String cacheRoot,
  required String path,
}) => RustLib.instance.api.crateApiGetSongCoverThumbnail(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  path: path,
);

Future<String> getSongCover({
  required String dbPath,
  required String cacheRoot,
  required String path,
}) => RustLib.instance.api.crateApiGetSongCover(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  path: path,
);

Future<String> extractSongCoverThumbnailFromFd({
  required String cacheRoot,
  required String path,
  required int fd,
}) => RustLib.instance.api.crateApiExtractSongCoverThumbnailFromFd(
  cacheRoot: cacheRoot,
  path: path,
  fd: fd,
);

Future<String> getSongLyricsPayload({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiGetSongLyricsPayload(
  dbPath: dbPath,
  path: path,
);

Future<String> getSongLyricsForEdit({required String path}) =>
    RustLib.instance.api.crateApiGetSongLyricsForEdit(path: path);

Future<String> saveSongLyrics({
  required String path,
  required String lyrics,
  required LyricsStorageSource source,
  String? sourcePath,
}) => RustLib.instance.api.crateApiSaveSongLyrics(
  path: path,
  lyrics: lyrics,
  source: source,
  sourcePath: sourcePath,
);

Future<String> getSongLyrics({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiGetSongLyrics(dbPath: dbPath, path: path);

Future<String> readLyricsFile({required String path}) =>
    RustLib.instance.api.crateApiReadLyricsFile(path: path);

Future<String> saveSongBackground({
  required String dbPath,
  required String songBackgroundsRoot,
  required String songPath,
  required String backgroundPath,
}) => RustLib.instance.api.crateApiSaveSongBackground(
  dbPath: dbPath,
  songBackgroundsRoot: songBackgroundsRoot,
  songPath: songPath,
  backgroundPath: backgroundPath,
);

Future<String> getSongBackground({
  required String dbPath,
  required String songPath,
}) => RustLib.instance.api.crateApiGetSongBackground(
  dbPath: dbPath,
  songPath: songPath,
);

Future<void> clearSongBackground({
  required String dbPath,
  required String songBackgroundsRoot,
  required String songPath,
}) => RustLib.instance.api.crateApiClearSongBackground(
  dbPath: dbPath,
  songBackgroundsRoot: songBackgroundsRoot,
  songPath: songPath,
);

Future<String> saveSongInfo({
  required String dbPath,
  required String path,
  required String payloadJson,
}) => RustLib.instance.api.crateApiSaveSongInfo(
  dbPath: dbPath,
  path: path,
  payloadJson: payloadJson,
);

Future<String> getSongDetail({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiGetSongDetail(dbPath: dbPath, path: path);

Future<void> savePlaybackSession({
  required String dbPath,
  required String sessionJson,
}) => RustLib.instance.api.crateApiSavePlaybackSession(
  dbPath: dbPath,
  sessionJson: sessionJson,
);

Future<String> loadPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiLoadPlaybackSession(dbPath: dbPath);

Future<String> sessionGetPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiSessionGetPlaybackSession(dbPath: dbPath);

Future<void> sessionFlushPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiSessionFlushPlaybackSession(dbPath: dbPath);

Future<void> updatePlaybackPosition({
  required String dbPath,
  required double positionSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiUpdatePlaybackPosition(
  dbPath: dbPath,
  positionSecs: positionSecs,
  isPlaying: isPlaying,
);

Future<String> previewRename({
  required String rootPath,
  required String configJson,
}) => RustLib.instance.api.crateApiPreviewRename(
  rootPath: rootPath,
  configJson: configJson,
);

Future<int> applyRename({required String operationsJson}) =>
    RustLib.instance.api.crateApiApplyRename(operationsJson: operationsJson);

Future<String> refreshFolderSongs({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiRefreshFolderSongs(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

Future<String> resolveDownloadFullPath({
  required String directory,
  required String title,
  required String artist,
  required String album,
  required String url,
  required String quality,
  required bool keepSourceFilename,
  required String fileNameStyle,
  required bool overwriteExisting,
}) => RustLib.instance.api.crateApiResolveDownloadFullPath(
  directory: directory,
  title: title,
  artist: artist,
  album: album,
  url: url,
  quality: quality,
  keepSourceFilename: keepSourceFilename,
  fileNameStyle: fileNameStyle,
  overwriteExisting: overwriteExisting,
);

Future<String> startUsbExclusivePlayback({
  required String path,
  required int deviceId,
  required double volume,
  required double startTimeSecs,
  required bool isPlaying,
  required double volumeBalanceGain,
  required String equalizerSettingsJson,
  required String soundEffectSettingsJson,
  required bool bitPerfect,
  required bool dsdNativePassthrough,
  required bool sharedMode,
}) => RustLib.instance.api.crateApiStartUsbExclusivePlayback(
  path: path,
  deviceId: deviceId,
  volume: volume,
  startTimeSecs: startTimeSecs,
  isPlaying: isPlaying,
  volumeBalanceGain: volumeBalanceGain,
  equalizerSettingsJson: equalizerSettingsJson,
  soundEffectSettingsJson: soundEffectSettingsJson,
  bitPerfect: bitPerfect,
  dsdNativePassthrough: dsdNativePassthrough,
  sharedMode: sharedMode,
);

Future<void> stopUsbExclusivePlayback() =>
    RustLib.instance.api.crateApiStopUsbExclusivePlayback();

Future<void> pauseUsbExclusive() =>
    RustLib.instance.api.crateApiPauseUsbExclusive();

Future<void> resumeUsbExclusive() =>
    RustLib.instance.api.crateApiResumeUsbExclusive();

Future<void> seekUsbExclusive({
  required double timeSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiSeekUsbExclusive(
  timeSecs: timeSecs,
  isPlaying: isPlaying,
);

Future<void> setUsbExclusiveVolume({required double volume}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveVolume(volume: volume);

Future<void> setUsbExclusiveVolumeBalanceGain({required double gain}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveVolumeBalanceGain(gain: gain);

Future<void> setUsbExclusiveEqualizer({required String settingsJson}) => RustLib
    .instance
    .api
    .crateApiSetUsbExclusiveEqualizer(settingsJson: settingsJson);

Future<void> setUsbExclusiveSoundEffect({required String settingsJson}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveSoundEffect(
      settingsJson: settingsJson,
    );

Future<void> setUsbExclusiveBitPerfect({required bool enabled}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveBitPerfect(enabled: enabled);

Future<bool> getUsbExclusiveBitPerfect() =>
    RustLib.instance.api.crateApiGetUsbExclusiveBitPerfect();

Future<String> getUsbExclusiveDeviceInfo() =>
    RustLib.instance.api.crateApiGetUsbExclusiveDeviceInfo();

Future<double> getUsbExclusivePositionSecs() =>
    RustLib.instance.api.crateApiGetUsbExclusivePositionSecs();

Future<String> downloadOnlineSong({
  required String url,
  required String destPath,
  String? ekey,
  required String headersJson,
}) => RustLib.instance.api.crateApiDownloadOnlineSong(
  url: url,
  destPath: destPath,
  ekey: ekey,
  headersJson: headersJson,
);

Future<String> decryptQmcFileStandalone({
  required String filePath,
  String? ekey,
}) => RustLib.instance.api.crateApiDecryptQmcFileStandalone(
  filePath: filePath,
  ekey: ekey,
);

Future<String> finalizeDownloadExtras({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiFinalizeDownloadExtras(requestJson: requestJson);

Future<String> readDownloadHistory({required String dataDir}) =>
    RustLib.instance.api.crateApiReadDownloadHistory(dataDir: dataDir);

Future<void> writeDownloadHistory({
  required String dataDir,
  required String content,
}) => RustLib.instance.api.crateApiWriteDownloadHistory(
  dataDir: dataDir,
  content: content,
);

Future<String> fetchAnnouncement() =>
    RustLib.instance.api.crateApiFetchAnnouncement();

Future<String> readPluginFile({required String path}) =>
    RustLib.instance.api.crateApiReadPluginFile(path: path);

Future<String> proxyImage({required String url, String? referer}) =>
    RustLib.instance.api.crateApiProxyImage(url: url, referer: referer);

Future<String> readImageBase64({required String path}) =>
    RustLib.instance.api.crateApiReadImageBase64(path: path);

Future<String> downloadVideoToCache({
  required String cacheDir,
  required String url,
  Map<String, String>? headers,
}) => RustLib.instance.api.crateApiDownloadVideoToCache(
  cacheDir: cacheDir,
  url: url,
  headers: headers,
);

Future<void> removeCachedBackgroundVideo({
  required String cacheDir,
  required String path,
}) => RustLib.instance.api.crateApiRemoveCachedBackgroundVideo(
  cacheDir: cacheDir,
  path: path,
);

Future<String> hostZzcSign({required String text}) =>
    RustLib.instance.api.crateApiHostZzcSign(text: text);

Future<String> hostKugouSign({
  required String params,
  required String platform,
  String? body,
}) => RustLib.instance.api.crateApiHostKugouSign(
  params: params,
  platform: platform,
  body: body,
);

Future<String> hostKugouRequestKey() =>
    RustLib.instance.api.crateApiHostKugouRequestKey();

Future<String> hostMiguSign({required String text, required String time}) =>
    RustLib.instance.api.crateApiHostMiguSign(text: text, time: time);

Future<String> hostLinuxapiEncrypt({required String payload}) =>
    RustLib.instance.api.crateApiHostLinuxapiEncrypt(payload: payload);

Future<String> hostWeapiEncrypt({required String payload}) =>
    RustLib.instance.api.crateApiHostWeapiEncrypt(payload: payload);

Future<String> hostSha256Hex({required String text}) =>
    RustLib.instance.api.crateApiHostSha256Hex(text: text);

Future<bool> verifyFallbackModuleSignature({
  required String moduleKey,
  required PlatformInt64 version,
  required String code,
  required String signature,
}) => RustLib.instance.api.crateApiVerifyFallbackModuleSignature(
  moduleKey: moduleKey,
  version: version,
  code: code,
  signature: signature,
);

Future<void> pluginEngineInit({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineInit(dataDir: dataDir);

Future<String> pluginEngineLoadLx({
  required String dataDir,
  required String pluginId,
  required String script,
  required String scriptInfoJson,
}) => RustLib.instance.api.crateApiPluginEngineLoadLx(
  dataDir: dataDir,
  pluginId: pluginId,
  script: script,
  scriptInfoJson: scriptInfoJson,
);

Future<String> pluginEngineLoadMusicfree({
  required String dataDir,
  required String pluginId,
  required String script,
  required String userVarsJson,
}) => RustLib.instance.api.crateApiPluginEngineLoadMusicfree(
  dataDir: dataDir,
  pluginId: pluginId,
  script: script,
  userVarsJson: userVarsJson,
);

Future<String> pluginEngineCall({
  required String dataDir,
  required String pluginId,
  required String method,
  required String argsJson,
  String? userVarsJson,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiPluginEngineCall(
  dataDir: dataDir,
  pluginId: pluginId,
  method: method,
  argsJson: argsJson,
  userVarsJson: userVarsJson,
  timeoutMs: timeoutMs,
);

Future<void> pluginEngineDestroy({
  required String dataDir,
  required String pluginId,
}) => RustLib.instance.api.crateApiPluginEngineDestroy(
  dataDir: dataDir,
  pluginId: pluginId,
);

Future<void> pluginEngineDestroyAll({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineDestroyAll(dataDir: dataDir);

Future<void> cancelRecognizeSystemAudio() =>
    RustLib.instance.api.crateApiCancelRecognizeSystemAudio();

Future<String> recognizeWithPcm({required List<int> pcm}) =>
    RustLib.instance.api.crateApiRecognizeWithPcm(pcm: pcm);

Future<void> setStreamCacheMaxSizeBytes({required BigInt bytes}) =>
    RustLib.instance.api.crateApiSetStreamCacheMaxSizeBytes(bytes: bytes);

Future<BigInt> streamCacheCurrentBytes() =>
    RustLib.instance.api.crateApiStreamCacheCurrentBytes();

Future<BigInt> streamCacheMaxBytes() =>
    RustLib.instance.api.crateApiStreamCacheMaxBytes();

Future<void> clearStreamCache() =>
    RustLib.instance.api.crateApiClearStreamCache();

Future<String> statsGetQualityDistribution({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetQualityDistribution(dbPath: dbPath);

Future<String> statsGetFormatDistribution({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetFormatDistribution(dbPath: dbPath);

Future<String> statsGetLibraryStats({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetLibraryStats(dbPath: dbPath);

Future<void> statsResetLocalStatistics({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsResetLocalStatistics(dbPath: dbPath);

Future<String> statsGetFavoriteArtistCatalog({
  required String dbPath,
  required List<String> favoritePaths,
}) => RustLib.instance.api.crateApiStatsGetFavoriteArtistCatalog(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
);

Future<String> statsGetFavoriteAlbumCatalog({
  required String dbPath,
  required List<String> favoritePaths,
}) => RustLib.instance.api.crateApiStatsGetFavoriteAlbumCatalog(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
);

Future<String> statsGetFavoriteSongPathsView({
  required String dbPath,
  required List<String> favoritePaths,
  String? query,
  required String sortMode,
  String? detailFilterType,
  String? detailFilterValue,
}) => RustLib.instance.api.crateApiStatsGetFavoriteSongPathsView(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
  query: query,
  sortMode: sortMode,
  detailFilterType: detailFilterType,
  detailFilterValue: detailFilterValue,
);

Future<String> statsGetRecentAlbumCatalog({
  required String dbPath,
  required String recentEntriesJson,
}) => RustLib.instance.api.crateApiStatsGetRecentAlbumCatalog(
  dbPath: dbPath,
  recentEntriesJson: recentEntriesJson,
);

Future<String> statsGetRecentSongPathsView({
  required String dbPath,
  required String recentEntriesJson,
  String? query,
  required String sortMode,
}) => RustLib.instance.api.crateApiStatsGetRecentSongPathsView(
  dbPath: dbPath,
  recentEntriesJson: recentEntriesJson,
  query: query,
  sortMode: sortMode,
);

Future<String> statsGetRecentPlaylistCatalog({
  required String playlistsJson,
  required String recentEntriesJson,
}) => RustLib.instance.api.crateApiStatsGetRecentPlaylistCatalog(
  playlistsJson: playlistsJson,
  recentEntriesJson: recentEntriesJson,
);

Future<void> clearCoverCache({required String cacheDir}) =>
    RustLib.instance.api.crateApiClearCoverCache(cacheDir: cacheDir);

Future<String> getLxCover({required String songInfoJson}) =>
    RustLib.instance.api.crateApiGetLxCover(songInfoJson: songInfoJson);

Future<void> clearLxUrlCache() =>
    RustLib.instance.api.crateApiClearLxUrlCache();

Future<void> clearLxAllCache() =>
    RustLib.instance.api.crateApiClearLxAllCache();

Future<String> findAlternativeLxSource({
  required String songName,
  required String songArtist,
  required double songDuration,
  required String failedSourcesJson,
}) => RustLib.instance.api.crateApiFindAlternativeLxSource(
  songName: songName,
  songArtist: songArtist,
  songDuration: songDuration,
  failedSourcesJson: failedSourcesJson,
);

Future<String> testRemoteSource({required String sourceJson}) =>
    RustLib.instance.api.crateApiTestRemoteSource(sourceJson: sourceJson);

Future<void> precacheRemoteSong({
  required String dbPath,
  required String cacheRoot,
  required String remoteUri,
}) => RustLib.instance.api.crateApiPrecacheRemoteSong(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  remoteUri: remoteUri,
);

Future<String> listRemoteDirectory({
  required String dbPath,
  required String sourceId,
  required String path,
}) => RustLib.instance.api.crateApiListRemoteDirectory(
  dbPath: dbPath,
  sourceId: sourceId,
  path: path,
);

Future<String> transcodeAudioToWav({
  required String dbPath,
  required String cacheRoot,
  required String srcPath,
}) => RustLib.instance.api.crateApiTranscodeAudioToWav(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  srcPath: srcPath,
);

Future<String> probeUrlSize({required String url}) =>
    RustLib.instance.api.crateApiProbeUrlSize(url: url);

Future<String> writeTextFile({
  required String content,
  required String destPath,
}) => RustLib.instance.api.crateApiWriteTextFile(
  content: content,
  destPath: destPath,
);

Future<String> fetchImageBytes({required String url}) =>
    RustLib.instance.api.crateApiFetchImageBytes(url: url);

Future<void> embedAudioMetadata({required String requestJson}) =>
    RustLib.instance.api.crateApiEmbedAudioMetadata(requestJson: requestJson);

Future<bool> isDirectory({required String path}) =>
    RustLib.instance.api.crateApiIsDirectory(path: path);

Future<String> saveArtistAvatar({
  required String dbPath,
  required String coversRoot,
  required PlatformInt64 artistId,
  required String imagePath,
  required bool writeToTags,
}) => RustLib.instance.api.crateApiSaveArtistAvatar(
  dbPath: dbPath,
  coversRoot: coversRoot,
  artistId: artistId,
  imagePath: imagePath,
  writeToTags: writeToTags,
);

Future<String> getLibrarySongPathsForAllView({
  required String dbPath,
  String? query,
  String? artistFilter,
  String? albumFilter,
  required String sortMode,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsForAllView(
  dbPath: dbPath,
  query: query,
  artistFilter: artistFilter,
  albumFilter: albumFilter,
  sortMode: sortMode,
);

Future<String> scanLibrary({
  required String dbPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiScanLibrary(
  dbPath: dbPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

Future<String> getFolderChildren({
  required String dbPath,
  required String folderPath,
}) => RustLib.instance.api.crateApiGetFolderChildren(
  dbPath: dbPath,
  folderPath: folderPath,
);

Future<String> getFolderFirstSong({
  required String dbPath,
  required String folderPath,
}) => RustLib.instance.api.crateApiGetFolderFirstSong(
  dbPath: dbPath,
  folderPath: folderPath,
);

Future<String> createFolder({
  required String parentPath,
  required String folderName,
}) => RustLib.instance.api.crateApiCreateFolder(
  parentPath: parentPath,
  folderName: folderName,
);

Future<void> deleteFolder({required String path}) =>
    RustLib.instance.api.crateApiDeleteFolder(path: path);

Future<void> moveFileToFolder({
  required String dbPath,
  required String sourcePath,
  required String targetFolder,
}) => RustLib.instance.api.crateApiMoveFileToFolder(
  dbPath: dbPath,
  sourcePath: sourcePath,
  targetFolder: targetFolder,
);

Future<String> batchMoveMusicFiles({
  required String dbPath,
  required List<String> paths,
  required String targetFolder,
}) => RustLib.instance.api.crateApiBatchMoveMusicFiles(
  dbPath: dbPath,
  paths: paths,
  targetFolder: targetFolder,
);

Future<void> moveMusicFile({
  required String dbPath,
  required String oldPath,
  required String newPath,
}) => RustLib.instance.api.crateApiMoveMusicFile(
  dbPath: dbPath,
  oldPath: oldPath,
  newPath: newPath,
);

Future<void> deleteMusicFile({required String path}) =>
    RustLib.instance.api.crateApiDeleteMusicFile(path: path);

Future<void> removeSongsFromHistoryAndStatistics({
  required String dbPath,
  required List<String> songPaths,
}) => RustLib.instance.api.crateApiRemoveSongsFromHistoryAndStatistics(
  dbPath: dbPath,
  songPaths: songPaths,
);

Future<String> resolveDownloadPath({
  required String directory,
  required String fileName,
  required bool overwriteExisting,
}) => RustLib.instance.api.crateApiResolveDownloadPath(
  directory: directory,
  fileName: fileName,
  overwriteExisting: overwriteExisting,
);

Future<String> buildDownloadBasename({
  required String title,
  required String artist,
  required String album,
  required String fileNameStyle,
}) => RustLib.instance.api.crateApiBuildDownloadBasename(
  title: title,
  artist: artist,
  album: album,
  fileNameStyle: fileNameStyle,
);

Future<String> saveDownloadBytes({
  required List<int> data,
  required String destPath,
}) => RustLib.instance.api.crateApiSaveDownloadBytes(
  data: data,
  destPath: destPath,
);

Future<String> saveDownloadLyrics({
  required String content,
  required String destPath,
}) => RustLib.instance.api.crateApiSaveDownloadLyrics(
  content: content,
  destPath: destPath,
);

Future<String> getStreamCacheInfo() =>
    RustLib.instance.api.crateApiGetStreamCacheInfo();

Future<bool> isStreamCached({required String url}) =>
    RustLib.instance.api.crateApiIsStreamCached(url: url);

Future<BigInt> copyStreamCache({
  required String url,
  required String destPath,
}) =>
    RustLib.instance.api.crateApiCopyStreamCache(url: url, destPath: destPath);

Future<bool> waitStreamComplete({
  required String url,
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiWaitStreamComplete(
  url: url,
  timeoutSecs: timeoutSecs,
);

Future<String> updateLoudnessSettings({
  required String dbPath,
  required bool enabled,
  PlatformInt64? songId,
  String? songPath,
  required double gainOffsetDb,
  required bool preventClipping,
}) => RustLib.instance.api.crateApiUpdateLoudnessSettings(
  dbPath: dbPath,
  enabled: enabled,
  songId: songId,
  songPath: songPath,
  gainOffsetDb: gainOffsetDb,
  preventClipping: preventClipping,
);

Future<String> mergeCloudListenDuration({
  required String dbPath,
  required PlatformInt64 totalSeconds,
}) => RustLib.instance.api.crateApiMergeCloudListenDuration(
  dbPath: dbPath,
  totalSeconds: totalSeconds,
);

Future<String> statsExportListenSnapshot({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsExportListenSnapshot(dbPath: dbPath);

Future<String> statsImportListenSnapshot({
  required String dbPath,
  required String snapshotJson,
}) => RustLib.instance.api.crateApiStatsImportListenSnapshot(
  dbPath: dbPath,
  snapshotJson: snapshotJson,
);

Future<String> statsImportListenSnapshotAdd({
  required String dbPath,
  required String snapshotJson,
}) => RustLib.instance.api.crateApiStatsImportListenSnapshotAdd(
  dbPath: dbPath,
  snapshotJson: snapshotJson,
);

Future<void> statsClearListenStats({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsClearListenStats(dbPath: dbPath);

Future<void> pluginEngineStoreImport({
  required String dataDir,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginEngineStoreImport(
  dataDir: dataDir,
  payloadJson: payloadJson,
);

Future<String> pluginEngineCookieHeaderForDomain({
  required String dataDir,
  required String domain,
}) => RustLib.instance.api.crateApiPluginEngineCookieHeaderForDomain(
  dataDir: dataDir,
  domain: domain,
);

Future<String> pluginEngineStoreSnapshot({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineStoreSnapshot(dataDir: dataDir);

Future<String> dlnaSearchDevices({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiDlnaSearchDevices(timeoutMs: timeoutMs);

Future<String> dlnaCastSetUri({
  required String deviceJson,
  required String mediaJson,
  String? coverJson,
  required String title,
  required String artist,
  required String album,
  required BigInt durationMs,
}) => RustLib.instance.api.crateApiDlnaCastSetUri(
  deviceJson: deviceJson,
  mediaJson: mediaJson,
  coverJson: coverJson,
  title: title,
  artist: artist,
  album: album,
  durationMs: durationMs,
);

Future<void> dlnaCastPlay({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastPlay(deviceJson: deviceJson);

Future<void> dlnaCastPause({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastPause(deviceJson: deviceJson);

Future<void> dlnaCastStop({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastStop(deviceJson: deviceJson);

Future<void> dlnaCastSeek({required String deviceJson, required double secs}) =>
    RustLib.instance.api.crateApiDlnaCastSeek(
      deviceJson: deviceJson,
      secs: secs,
    );

Future<void> dlnaCastSetVolume({
  required String deviceJson,
  required int percent,
}) => RustLib.instance.api.crateApiDlnaCastSetVolume(
  deviceJson: deviceJson,
  percent: percent,
);

Future<String> dlnaCastGetState({required String deviceJson}) =>
    RustLib.instance.api.crateApiDlnaCastGetState(deviceJson: deviceJson);

Future<bool> dlnaUpdateMediaToken({
  required String token,
  required String payloadJson,
}) => RustLib.instance.api.crateApiDlnaUpdateMediaToken(
  token: token,
  payloadJson: payloadJson,
);

Future<int> dlnaEnableRenderer({
  required String friendlyName,
  required String udn,
}) => RustLib.instance.api.crateApiDlnaEnableRenderer(
  friendlyName: friendlyName,
  udn: udn,
);

Future<void> dlnaDisableRenderer() =>
    RustLib.instance.api.crateApiDlnaDisableRenderer();

Future<String> dlnaRendererStatus() =>
    RustLib.instance.api.crateApiDlnaRendererStatus();

Future<String?> dlnaDmrNextCommand({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiDlnaDmrNextCommand(timeoutMs: timeoutMs);

Future<void> dlnaDmrReportPlayback({
  required String state,
  required double positionSecs,
  required double durationSecs,
  required int volumePercent,
  required bool muted,
}) => RustLib.instance.api.crateApiDlnaDmrReportPlayback(
  state: state,
  positionSecs: positionSecs,
  durationSecs: durationSecs,
  volumePercent: volumePercent,
  muted: muted,
);

Future<String> convertAudioBatch({
  required List<String> inputPaths,
  required String outDir,
  required String optionsJson,
}) => RustLib.instance.api.crateApiConvertAudioBatch(
  inputPaths: inputPaths,
  outDir: outDir,
  optionsJson: optionsJson,
);

Future<List<String>> audioConvertSupportedInputs() =>
    RustLib.instance.api.crateApiAudioConvertSupportedInputs();

Future<List<String>> audioConvertSupportedOutputs() =>
    RustLib.instance.api.crateApiAudioConvertSupportedOutputs();

class WebdavSourceOverrides {
  final String? baseUrl;
  final String? username;
  final String? rootPath;

  const WebdavSourceOverrides({this.baseUrl, this.username, this.rootPath});

  static Future<WebdavSourceOverrides> default_() =>
      RustLib.instance.api.crateApiWebdavSourceOverridesDefault();

  @override
  int get hashCode => baseUrl.hashCode ^ username.hashCode ^ rootPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebdavSourceOverrides &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          username == other.username &&
          rootPath == other.rootPath;
}
